/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniludoteca.vista;

import java.util.ArrayList;
import java.util.Collections;
import miniludoteca.modelo.Jugador;

/**
 *
 * @author jvigual
 */
public class Clasificacion extends javax.swing.JFrame {
    private ArrayList<Jugador> jugadores;
    

    public Clasificacion(ArrayList<Jugador> jugadores) {
        initComponents();
        
        this.jugadores = new ArrayList<>(jugadores);
        
        Collections.sort(this.jugadores, Collections.reverseOrder());
        int i = 1;
        String resultado = "";
        for (Jugador jugador: this.jugadores) {
            resultado += i++ + ". " + jugador.nombre() + " - " + jugador.fichasAcumuladas() + "\n";
        }
        this.clasificacionTextArea.setText(resultado);
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clasificacionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clasificación");

        clasificacionTextArea.setColumns(20);
        clasificacionTextArea.setRows(5);
        clasificacionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(clasificacionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea clasificacionTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
