/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniludoteca.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import miniludoteca.modelo.Jugador;

/**
 *
 * @author jvigual
 */
public class VistaHistorico extends javax.swing.JFrame {
    private ArrayList<Jugador> jugadores;
    private DefaultTableModel modeloTablaJugadores;
    
    public VistaHistorico(ArrayList<Jugador> jugadores) {
        initComponents();
        
        this.jugadores = jugadores;
        
        this.modeloTablaJugadores = new DefaultTableModel(new String[]{"Nombre", "Fichas Acumuladas", "Ganadas BJ", "Empatadas BJ", "Perdidas BJ", "Ganadas SM", "Perdidas SM"}, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }  
        };
        for (Jugador jugador: this.jugadores) {
            this.modeloTablaJugadores.addRow(new Object[]{jugador.nombre(), jugador.fichasAcumuladas(), jugador.resumenJuegoBlackJack().partidasGanadas(), jugador.resumenJuegoBlackJack().partidasEmpatadas(), jugador.resumenJuegoBlackJack().partidasPerdidas(), jugador.resumenJuego().partidasGanadas(), jugador.resumenJuego().partidasPerdidas()});
        }
        this.jugadoresTable.setModel(this.modeloTablaJugadores);
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jugadoresTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histórico");

        jugadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fichas", "Ganadas BJ", "Empatadas BJ", "Perdidas BJ", "Ganadas SM", "Perdidas SM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jugadoresTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jugadoresTable;
    // End of variables declaration//GEN-END:variables
}
